{{- with .Values.pgadminSecrets }}
{{- if .enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-credentials
  namespace: {{ .namespace }}
  labels:
    {{- include "insanefly-platform.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: pgadmin-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: pgadmin/credentials
        property: password
{{- end }}
{{- end }}
