apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres
spec:
  instances: 3

  bootstrap:
    initdb:
      database: ferriskey
      owner: ferriskey
      secret:
        name: ferriskey-db-secret

  storage:
    size: 1Gi
