apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/bank-vaults/helm-charts/vault-operator
    targetRevision: 1.24.0
    chart: vault-operator
    helm:
      releaseName: vault-operator
      values: |
        # vault-operator defaults
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
