apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/dinosath/insanefly-argocd-apps
    targetRevision: main
    path: platform/secret-store
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
