apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.3.1
    chart: clickhouse
    helm:
      releaseName: clickhouse
      values: |
        shards: 1
        replicaCount: 1
        image:
          registry: docker.io
          repository: bitnamilegacy/clickhouse
          tag: 23.3.2-debian-11-r6
        auth:
          username: vector
          existingSecret: clickhouse
          existingSecretKey: admin-password
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 750m
            memory: 1Gi
        zookeeper:
          enabled: false
        initdbScripts:
          01-init-vector.sql: |
            CREATE DATABASE IF NOT EXISTS vector;
            CREATE TABLE IF NOT EXISTS vector.logs
            (
              timestamp DateTime64(3, 'UTC') DEFAULT now64(3),
              message String,
              host String,
              namespace String,
              pod String,
              container String,
              source_type String,
              raw String
            )
            ENGINE = MergeTree
            ORDER BY timestamp;
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
