apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/dinosath/insanefly-argocd-apps
    targetRevision: main
    path: helm/external-secrets
    helm:
      releaseName: external-secrets
      values: |
        ferriskeySecrets:
          enabled: true
          clusterSecretStoreName: vault-kv
          postgresNamespace: postgres
          ferriskeyNamespace: ferriskey
        clickhouseSecrets:
          enabled: true
          namespace: clickhouse
          clusterSecretStoreName: vault-kv
        vectorSecrets:
          enabled: true
          namespace: vector
          clusterSecretStoreName: vault-kv
        pgadminSecrets:
          namespace: pgadmin
        coderSecrets:
          enabled: true
          postgresNamespace: postgres
          coderNamespace: coder
          clusterSecretStoreName: vault-kv
          dbSecretName: coder-db-secret
          dbUrlSecretName: coder-db-url
          database: coder
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
