apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-vaults-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/bank-vaults/helm-charts
    chart: vault-operator
    targetRevision: 1.24.0
    helm:
      releaseName: vault-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: vault-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
